// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/collector/document.proto

package collector

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 文档抓取的请求
type DocumentScrapeRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Keyword              string   `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentScrapeRequest) Reset()         { *m = DocumentScrapeRequest{} }
func (m *DocumentScrapeRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentScrapeRequest) ProtoMessage()    {}
func (*DocumentScrapeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2164e8c8015e4c3, []int{0}
}

func (m *DocumentScrapeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentScrapeRequest.Unmarshal(m, b)
}
func (m *DocumentScrapeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentScrapeRequest.Marshal(b, m, deterministic)
}
func (m *DocumentScrapeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentScrapeRequest.Merge(m, src)
}
func (m *DocumentScrapeRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentScrapeRequest.Size(m)
}
func (m *DocumentScrapeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentScrapeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentScrapeRequest proto.InternalMessageInfo

func (m *DocumentScrapeRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DocumentScrapeRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type DocumentListResponse struct {
	Status               *Status           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64             `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*DocumentEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DocumentListResponse) Reset()         { *m = DocumentListResponse{} }
func (m *DocumentListResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentListResponse) ProtoMessage()    {}
func (*DocumentListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2164e8c8015e4c3, []int{1}
}

func (m *DocumentListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentListResponse.Unmarshal(m, b)
}
func (m *DocumentListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentListResponse.Marshal(b, m, deterministic)
}
func (m *DocumentListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentListResponse.Merge(m, src)
}
func (m *DocumentListResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentListResponse.Size(m)
}
func (m *DocumentListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentListResponse proto.InternalMessageInfo

func (m *DocumentListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DocumentListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DocumentListResponse) GetEntity() []*DocumentEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*DocumentScrapeRequest)(nil), "collector.DocumentScrapeRequest")
	proto.RegisterType((*DocumentListResponse)(nil), "collector.DocumentListResponse")
}

func init() {
	proto.RegisterFile("proto/collector/document.proto", fileDescriptor_a2164e8c8015e4c3)
}

var fileDescriptor_a2164e8c8015e4c3 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x1b, 0x02, 0x81, 0x4e, 0x57, 0x8c, 0x0a, 0x0a, 0x15, 0x82, 0x28, 0xab, 0xb2, 0x49,
	0x45, 0x38, 0x01, 0x08, 0xd8, 0xc0, 0xca, 0x3d, 0x81, 0x89, 0x47, 0xa2, 0x6a, 0x88, 0x83, 0x3d,
	0x11, 0xea, 0x15, 0xd8, 0x73, 0x5f, 0x54, 0x3b, 0xae, 0x02, 0xea, 0x72, 0xf4, 0xde, 0x7c, 0xfb,
	0x0f, 0x5c, 0xb5, 0x46, 0xb3, 0x5e, 0x54, 0xba, 0xae, 0xa9, 0x62, 0x6d, 0x16, 0x4a, 0x57, 0xdd,
	0x07, 0x35, 0x5c, 0x38, 0x80, 0xe3, 0x1d, 0x99, 0x5d, 0xfe, 0x57, 0xed, 0xbb, 0x34, 0xa4, 0xbc,
	0x98, 0xbf, 0xc0, 0xd9, 0x63, 0xbf, 0xba, 0xac, 0x8c, 0x6c, 0x49, 0xd0, 0x67, 0x47, 0x96, 0x31,
	0x85, 0x63, 0xa9, 0x94, 0x21, 0x6b, 0xd3, 0x28, 0x8b, 0xe6, 0x63, 0x11, 0xc6, 0x2d, 0x59, 0xd3,
	0xe6, 0x4b, 0x1b, 0x95, 0x1e, 0x78, 0xd2, 0x8f, 0xf9, 0x77, 0x04, 0xd3, 0x90, 0xf6, 0xba, 0xb2,
	0x2c, 0xc8, 0xb6, 0xba, 0xb1, 0x84, 0x37, 0x90, 0x58, 0x96, 0xdc, 0xf9, 0xac, 0x49, 0x79, 0x5a,
	0xec, 0xbe, 0x53, 0x2c, 0x1d, 0x10, 0xbd, 0x80, 0x53, 0x38, 0x62, 0xcd, 0xb2, 0x76, 0xd9, 0xb1,
	0xf0, 0x03, 0xde, 0x42, 0x42, 0x0d, 0xaf, 0x78, 0x93, 0xc6, 0x59, 0x3c, 0x9f, 0x94, 0x17, 0x83,
	0x80, 0xf0, 0xe2, 0x93, 0x13, 0x44, 0x2f, 0x96, 0x3f, 0x11, 0x9c, 0x04, 0x84, 0xcf, 0x90, 0xf8,
	0x7a, 0x98, 0xed, 0xd9, 0xfc, 0xd3, 0x7c, 0x96, 0x0e, 0x8c, 0x87, 0x5a, 0x36, 0xeb, 0x50, 0x23,
	0x1f, 0xe1, 0x3d, 0x1c, 0x6e, 0x8b, 0xe1, 0xf9, 0xc0, 0xf1, 0x4d, 0xfd, 0xee, 0xf5, 0x9e, 0xf4,
	0xe1, 0x25, 0xf2, 0xd1, 0x5b, 0xe2, 0x0e, 0x7f, 0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x59, 0x38,
	0xd8, 0x58, 0xc3, 0x01, 0x00, 0x00,
}
