// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/collector/document.proto

package collector

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 文档抓取的请求
type DocumentScrapeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Keyword              []string `protobuf:"bytes,2,rep,name=keyword,proto3" json:"keyword,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Attribute            string   `protobuf:"bytes,4,opt,name=attribute,proto3" json:"attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentScrapeRequest) Reset()         { *m = DocumentScrapeRequest{} }
func (m *DocumentScrapeRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentScrapeRequest) ProtoMessage()    {}
func (*DocumentScrapeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2164e8c8015e4c3, []int{0}
}

func (m *DocumentScrapeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentScrapeRequest.Unmarshal(m, b)
}
func (m *DocumentScrapeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentScrapeRequest.Marshal(b, m, deterministic)
}
func (m *DocumentScrapeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentScrapeRequest.Merge(m, src)
}
func (m *DocumentScrapeRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentScrapeRequest.Size(m)
}
func (m *DocumentScrapeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentScrapeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentScrapeRequest proto.InternalMessageInfo

func (m *DocumentScrapeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DocumentScrapeRequest) GetKeyword() []string {
	if m != nil {
		return m.Keyword
	}
	return nil
}

func (m *DocumentScrapeRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DocumentScrapeRequest) GetAttribute() string {
	if m != nil {
		return m.Attribute
	}
	return ""
}

// 文档整理的请求
type DocumentTidyRequest struct {
	Uuid                 string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Host                 string            `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Rule                 map[string]string `protobuf:"bytes,3,rep,name=rule,proto3" json:"rule,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DocumentTidyRequest) Reset()         { *m = DocumentTidyRequest{} }
func (m *DocumentTidyRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentTidyRequest) ProtoMessage()    {}
func (*DocumentTidyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2164e8c8015e4c3, []int{1}
}

func (m *DocumentTidyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentTidyRequest.Unmarshal(m, b)
}
func (m *DocumentTidyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentTidyRequest.Marshal(b, m, deterministic)
}
func (m *DocumentTidyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentTidyRequest.Merge(m, src)
}
func (m *DocumentTidyRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentTidyRequest.Size(m)
}
func (m *DocumentTidyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentTidyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentTidyRequest proto.InternalMessageInfo

func (m *DocumentTidyRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DocumentTidyRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DocumentTidyRequest) GetRule() map[string]string {
	if m != nil {
		return m.Rule
	}
	return nil
}

type DocumentListResponse struct {
	Status               *Status           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64             `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*DocumentEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DocumentListResponse) Reset()         { *m = DocumentListResponse{} }
func (m *DocumentListResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentListResponse) ProtoMessage()    {}
func (*DocumentListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2164e8c8015e4c3, []int{2}
}

func (m *DocumentListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentListResponse.Unmarshal(m, b)
}
func (m *DocumentListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentListResponse.Marshal(b, m, deterministic)
}
func (m *DocumentListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentListResponse.Merge(m, src)
}
func (m *DocumentListResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentListResponse.Size(m)
}
func (m *DocumentListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentListResponse proto.InternalMessageInfo

func (m *DocumentListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DocumentListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DocumentListResponse) GetEntity() []*DocumentEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

// 文档删除的请求
type DocumentDeleteRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentDeleteRequest) Reset()         { *m = DocumentDeleteRequest{} }
func (m *DocumentDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentDeleteRequest) ProtoMessage()    {}
func (*DocumentDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2164e8c8015e4c3, []int{3}
}

func (m *DocumentDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentDeleteRequest.Unmarshal(m, b)
}
func (m *DocumentDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentDeleteRequest.Marshal(b, m, deterministic)
}
func (m *DocumentDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentDeleteRequest.Merge(m, src)
}
func (m *DocumentDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentDeleteRequest.Size(m)
}
func (m *DocumentDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentDeleteRequest proto.InternalMessageInfo

func (m *DocumentDeleteRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*DocumentScrapeRequest)(nil), "collector.DocumentScrapeRequest")
	proto.RegisterType((*DocumentTidyRequest)(nil), "collector.DocumentTidyRequest")
	proto.RegisterMapType((map[string]string)(nil), "collector.DocumentTidyRequest.RuleEntry")
	proto.RegisterType((*DocumentListResponse)(nil), "collector.DocumentListResponse")
	proto.RegisterType((*DocumentDeleteRequest)(nil), "collector.DocumentDeleteRequest")
}

func init() {
	proto.RegisterFile("proto/collector/document.proto", fileDescriptor_a2164e8c8015e4c3)
}

var fileDescriptor_a2164e8c8015e4c3 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x63, 0x63, 0xf0, 0xf4, 0x02, 0x43, 0x41, 0x26, 0xaa, 0x4a, 0xe4, 0x53, 0x10, 0x52,
	0x2a, 0xc2, 0x01, 0x84, 0xb8, 0x50, 0xb5, 0x3d, 0x71, 0xda, 0xf2, 0x02, 0xdb, 0x78, 0xa4, 0x5a,
	0x71, 0xbd, 0x61, 0x77, 0x16, 0xe4, 0x03, 0x2f, 0xc0, 0x5b, 0xf0, 0x0e, 0x3c, 0x20, 0xda, 0x5d,
	0x3b, 0x75, 0x90, 0xe5, 0xdb, 0xfc, 0x7c, 0xf3, 0x7d, 0x3b, 0xdf, 0xd8, 0x70, 0xb6, 0xd3, 0x8a,
	0xd5, 0xf9, 0x46, 0xd5, 0x35, 0x6d, 0x58, 0xe9, 0xf3, 0x52, 0x6d, 0xec, 0x3d, 0x35, 0xbc, 0xf2,
	0x0d, 0xcc, 0xf6, 0x9d, 0xf9, 0xe9, 0xff, 0x50, 0x73, 0x27, 0x35, 0x95, 0x01, 0x58, 0xfc, 0x82,
	0x17, 0x97, 0xdd, 0xe8, 0xcd, 0x46, 0xcb, 0x1d, 0x09, 0xfa, 0x6e, 0xc9, 0x30, 0x22, 0x24, 0x8d,
	0xbc, 0xa7, 0x3c, 0x5a, 0x44, 0xcb, 0x4c, 0xf8, 0x18, 0x73, 0x78, 0xbc, 0xa5, 0xf6, 0xa7, 0xd2,
	0x65, 0x3e, 0x5b, 0xc4, 0xcb, 0x4c, 0xf4, 0xa9, 0xeb, 0xc8, 0xb2, 0xd4, 0x64, 0x4c, 0x1e, 0xfb,
	0x81, 0x3e, 0xc5, 0x53, 0xc8, 0x24, 0xb3, 0xae, 0x6e, 0x2d, 0x53, 0x9e, 0xf8, 0xde, 0x43, 0xa1,
	0xf8, 0x1b, 0xc1, 0xf3, 0x5e, 0xff, 0x5b, 0x55, 0xb6, 0x03, 0x75, 0x6b, 0xab, 0xb2, 0x57, 0x77,
	0xb1, 0xab, 0xdd, 0x29, 0xc3, 0xf9, 0x2c, 0xd4, 0x5c, 0x8c, 0x9f, 0x21, 0xd1, 0xb6, 0xa6, 0x3c,
	0x5e, 0xc4, 0xcb, 0xe3, 0xf5, 0x72, 0xb5, 0xdf, 0x72, 0x35, 0xc2, 0xba, 0x12, 0xb6, 0xa6, 0xab,
	0x86, 0x75, 0x2b, 0xfc, 0xd4, 0xfc, 0x03, 0x64, 0xfb, 0x12, 0x3e, 0x85, 0x78, 0x4b, 0x6d, 0xa7,
	0xe8, 0x42, 0x3c, 0x81, 0x47, 0x3f, 0x64, 0x6d, 0xa9, 0x53, 0x0c, 0xc9, 0xa7, 0xd9, 0xc7, 0xa8,
	0xf8, 0x1d, 0xc1, 0x49, 0x2f, 0xf0, 0xb5, 0x32, 0x2c, 0xc8, 0xec, 0x54, 0x63, 0x08, 0xdf, 0x40,
	0x6a, 0x58, 0xb2, 0x35, 0x9e, 0xe7, 0x78, 0xfd, 0x6c, 0xf0, 0xa2, 0x1b, 0xdf, 0x10, 0x1d, 0xc0,
	0xb1, 0xb3, 0x62, 0x59, 0x7b, 0xf6, 0x58, 0x84, 0x04, 0xdf, 0x41, 0x4a, 0x0d, 0x57, 0xdc, 0x76,
	0x2b, 0xbd, 0x1a, 0x59, 0xe9, 0xca, 0x03, 0x44, 0x07, 0x2c, 0xde, 0x3e, 0x9c, 0xf0, 0x92, 0x6a,
	0x62, 0x9a, 0x30, 0x71, 0xfd, 0x67, 0x06, 0x4f, 0x7a, 0x34, 0x5e, 0x43, 0x1a, 0x8e, 0x8e, 0x8b,
	0x11, 0x99, 0x83, 0xef, 0x61, 0x9e, 0x0f, 0x10, 0x17, 0xb5, 0x6c, 0xb6, 0xfd, 0xce, 0xc5, 0x11,
	0x7e, 0x81, 0xc4, 0xb9, 0x80, 0x2f, 0x07, 0x98, 0x60, 0x4b, 0x98, 0x7d, 0x3d, 0xc2, 0x3e, 0xb4,
	0xad, 0x38, 0xc2, 0x0b, 0x48, 0xdc, 0xa5, 0xf0, 0x6c, 0xfa, 0x84, 0x93, 0xcf, 0xb8, 0x86, 0x34,
	0x18, 0x30, 0xba, 0xce, 0x81, 0x37, 0x53, 0x3c, 0xb7, 0xa9, 0xff, 0x35, 0xde, 0xff, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0x25, 0x8f, 0xea, 0x65, 0x03, 0x00, 0x00,
}
